let canvas = document.createElement('canvas')
let grapher = new Graph(canvas, [-5,5], [-1,1], 500)
grapher.appendTo(document.body)
grapher.clear()
grapher.drawAxes()
grapher.graphNormalCurve(0, 1, '#0000ff')